#!groovy

pipeline {
    agent any 

    stages {

        stage('pull'){
            steps {
                sh "docker pull ${dockerRegistry}/${image}"
            }
        }
        
        stage('undeploy') {
            steps {
                script {
                    try {
                        sh "docker stop ${image}"
                    } catch(Exception e) {
                    }
                    try {
                        sh "docker rm ${image}"
                    } catch(Exception e) {
                    }
                    try {
                        sh "docker rmi ${dockerRegistry}/${image}"
                    } catch(Exception e) {
                    }
                }
            }
        }
       
        stage('docker run') {
            steps {
                sh "docker run -itd -m 1024m --memory-swap 1024m --name ${image} --net softleader ${dockerRegistry}/${image}"
            }
        }
    }
}
